//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aloe.DB_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Main_Entities : DbContext
    {
        public DB_Main_Entities()
            : base("name=DB_Main_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DealPoint> DealPoints { get; set; }
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<LOITemplatePoint> LOITemplatePoints { get; set; }
        public virtual DbSet<LOITemplate> LOITemplates { get; set; }
        public virtual DbSet<MLOITemplatePoint> MLOITemplatePoints { get; set; }
        public virtual DbSet<MLOITemplate> MLOITemplates { get; set; }
        public virtual DbSet<DealMessage> DealMessages { get; set; }
        public virtual DbSet<DealHistory> DealHistories { get; set; }
    }
}
