//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aloe.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealMessage
    {
        public int ID { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Message { get; set; }
        public int Status { get; set; }
        public int DealID { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
