//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aloe.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealHistory
    {
        public int ID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string EntityName { get; set; }
        public string DealID { get; set; }
        public string UserID { get; set; }
        public string HistoryMessage { get; set; }
        public int historyStatus { get; set; }
        public bool HistoryNotification { get; set; }
    }
}
